//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication52
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CustomerID { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> Age { get; set; }
        public string City { get; set; }
        public Nullable<int> Phone { get; set; }
        public string Email { get; set; }
        public string Photo { get; set; }
        public Nullable<int> CityID { get; set; }
    
        public virtual City City1 { get; set; }
    }
}
